### ISSUE TITLE
Sửa

### ISSUE THREAD

**Issue by duthanhduoc** [minhan1910/image-magnifier-effect#1]
Nhớ thay thế src img ảnh

index.html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Image Zoom on Hover</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <div class="slider">
      <div class="active-image-wrapper" id="imageWrapper">
        <div class="wrapper-image" id="zoomContainer">
          <img
            src="./dotnet-la-gi-thumbail.jpg"
            alt="Zoomable Image"
            id="zoomImage"
            class="active-slide-item-image"
          />
        </div>
      </div>
    </div>
    <script src="script.js"></script>
  </body>
</html>

```

styles.css

```css
.slider {
  max-width: 1000px;
  margin: 4rem auto;
}

.active-image-wrapper {
  overflow: hidden;
  width: 100%;
  padding-bottom: 56.25%; /* Tỷ lệ 16:9 */
  position: relative;
  cursor: zoom-in;
}

.wrapper-image {
  position: absolute;
}

.active-slide-item-image {
  width: 100%;
  height: auto;
  object-fit: cover;
  max-width: 100%;
}

```

script.js

```js
document.addEventListener('DOMContentLoaded', () => {
  const imageWrapper = document.getElementById('imageWrapper')
  const zoomContainer = document.getElementById('zoomContainer')
  const zoomImage = document.getElementById('zoomImage')

  // Lấy kích thước tự nhiên của ảnh
  const naturalWidth = zoomImage.naturalWidth
  const naturalHeight = zoomImage.naturalHeight

  imageWrapper.addEventListener('mousemove', (event) => {
    // Chỉ zoom trên màn hình lớn hơn 1024px (theo logic React gốc)
    const rect = imageWrapper.getBoundingClientRect()
    const offsetX = event.pageX - (rect.left + window.scrollX)
    const offsetY = event.pageY - (rect.top + window.scrollY)

    // Tính toán vị trí và kích thước để zoom
    const top = -offsetY * (naturalHeight / rect.height - 1)
    const left = -offsetX * (naturalWidth / rect.width - 1)

    // Áp dụng style cho zoomContainer
    zoomContainer.style.top = `${top}px`
    zoomContainer.style.left = `${left}px`
    zoomContainer.style.width = `${naturalWidth}px`
    zoomContainer.style.height = `${naturalHeight}px`
  })

  imageWrapper.addEventListener('mouseout', () => {
    // Reset style khi chuột rời khỏi ảnh
    zoomContainer.style.removeProperty('top')
    zoomContainer.style.removeProperty('left')
    zoomContainer.style.removeProperty('width')
    zoomContainer.style.removeProperty('height')
  })
})

```
